esphome:
  name: guition-esp32-jc4827w543c
  friendly_name: Guition ESP32 Stream Deck
  project:
    name: "Guition.ESP32-jc4827w543C"
    version: "1.0"
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  flash_size: 4MB
  framework:
    type: esp-idf
    sdkconfig_options:
      COMPILER_OPTIMIZATION_SIZE: y
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: "y"
      CONFIG_ESP32S3_DATA_CACHE_64KB: "y"
      CONFIG_ESP32S3_DATA_CACHE_LINE_64B: "y"
      CONFIG_SPIRAM_FETCH_INSTRUCTIONS: y
      CONFIG_SPIRAM_RODATA: y
    advanced:
      assertion_level: DISABLE
      enable_lwip_mdns_queries: false
      enable_lwip_bridge_interface: false

psram:
  mode: octal
  speed: 80MHz

preferences:
  flash_write_interval: 5min

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key

# Set OTA password
ota:
  platform: esphome
  password: !secret ota_password

# WiFi configuration
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

captive_portal:

# Font configuration
font:
  - file:
      path: fonts/Arimo-Regular.ttf
      type: local
    id: arimo48
    size: 42
    glyphs:
      - " .,°0123456789CF"
  - file:
      path: fonts/Arimo-Regular.ttf
      type: local
    id: arimo14
    size: 14
    glyphs:
      - "0123456789"
  - file: fonts/materialdesignicons-webfont.ttf
    id: font_mdi
    size: 45
    glyphs:
      - "󰏘"
      - "󱁑"
      - "󰤝"
      - "󰈐"
      - "󱩋"
      - "󰠝"
      - "󱟉"

# Color configuration
color:
  - id: room_bg_color
    hex: "00050d"
  - id: default_button_bg_color
    hex: "00050d"
  - id: default_button_pressed_bg_color
    hex: "D3D3D3"
  - id: btn_1_txt_color
    hex: FF0000
  - id: btn_2_txt_color
    hex: FF7F00
  - id: btn_3_txt_color
    hex: FFFF00
  - id: btn_4_txt_color
    hex: 00FF00
  - id: btn_5_txt_color
    hex: FF1493
  - id: btn_6_txt_color
    hex: 800080
  - id: btn_7_txt_color
    hex: 0000FF
  - id: btn_8_txt_color
    hex: 00FFFF
  - id: btn_9_txt_color
    hex: FFFFFF
  - id: btn_10_txt_color
    hex: FFFFFF
  - id: btn_11_txt_color
    hex: FFFFFF
  - id: btn_12_txt_color
    hex: FFFFFF

# Backlight configuration
output:
  - platform: ledc
    pin:
      number: 1
    id: gpio_backlight_pwm
    frequency: 1000Hz

light:
  - platform: monochromatic
    output: gpio_backlight_pwm
    name: Display Backlight
    icon: mdi:lightbulb-on
    id: display_backlight
    restore_mode: ALWAYS_ON

# Binary sensors for buttons
binary_sensor:
  - platform: template
    name: Button 1
    id: button_1_pressed
  - platform: template
    name: Button 2
    id: button_2_pressed
  - platform: template
    name: Button 3
    id: button_3_pressed
  - platform: template
    name: Button 4
    id: button_4_pressed
  - platform: template
    name: Button 5
    id: button_5_pressed
  - platform: template
    name: Button 6
    id: button_6_pressed
  - platform: template
    name: Button 7
    id: button_7_pressed
  - platform: template
    name: Button 8
    id: button_8_pressed
  - platform: template
    name: Button 9
    id: button_9_pressed
  - platform: template
    name: Button 10
    id: button_10_pressed
  - platform: template
    name: Button 11
    id: button_11_pressed
  - platform: template
    name: Button 12
    id: button_12_pressed

# Text sensor for light state
text_sensor:
  - platform: homeassistant
    id: ts_switch_living
    entity_id: switch.0x282c02bfffed1ce8
    on_value:
      then:
        - lvgl.widget.update:
            id: btn_1
            state:
              checked: !lambda return (0 == x.compare(std::string{"on"}));
              disabled: !lambda return ((0 == x.compare(std::string{"unavailable"})) or (0 == x.compare(std::string{"unknown"})));
        - lvgl.label.update:
            id: lbl_btn_1
            text: !lambda |-
              static char buf[10];
              std::string icon;
              if (0 == x.compare(std::string{"on"})) {
                  icon = "󰤝";
              } else {
                  icon = "󱟉";
              }
              snprintf(buf, sizeof(buf), "%s", icon.c_str());
              return buf;
  - platform: homeassistant
    id: REDACTED
    entity_id: REDACTED
    on_value:
      then:
        - lvgl.widget.update:
            id: btn_2
            state:
              checked: !lambda return (0 == x.compare(std::string{"on"}));
              disabled: !lambda return ((0 == x.compare(std::string{"unavailable"})) or (0 == x.compare(std::string{"unknown"})));
        - lvgl.label.update:
            id: lbl_btn_2
            text: !lambda |-
              static char buf[10];
              std::string icon;
              if (0 == x.compare(std::string{"on"})) {
                  icon = "󰤝";
              } else {
                  icon = "󱟉";
              }
              snprintf(buf, sizeof(buf), "%s", icon.c_str());
              return buf;
  - platform: homeassistant
    id: REDACTED
    entity_id: REDACTED
    on_value:
      then:
        - lvgl.widget.update:
            id: btn_3
            state:
              checked: !lambda return (0 == x.compare(std::string{"on"}));
              disabled: !lambda return ((0 == x.compare(std::string{"unavailable"})) or (0 == x.compare(std::string{"unknown"})));
        - lvgl.label.update:
            id: lbl_btn_3
            text: !lambda |-
              static char buf[10];
              std::string icon;
              if (0 == x.compare(std::string{"on"})) {
                  icon = "󰤝";
              } else {
                  icon = "󱟉";
              }
              snprintf(buf, sizeof(buf), "%s", icon.c_str());
              return buf;
  - platform: homeassistant
    id: REDACTED
    entity_id: REDACTED
    on_value:
      then:
        - lvgl.widget.update:
            id: btn_4
            state:
              checked: !lambda return (0 == x.compare(std::string{"on"}));
              disabled: !lambda return ((0 == x.compare(std::string{"unavailable"})) or (0 == x.compare(std::string{"unknown"})));
        - lvgl.label.update:
            id: lbl_btn_4
            text: !lambda |-
              static char buf[10];
              std::string icon;
              if (0 == x.compare(std::string{"on"})) {
                  icon = "󰤝";
              } else {
                  icon = "󱟉";
              }
              snprintf(buf, sizeof(buf), "%s", icon.c_str());
              return buf;
  - platform: homeassistant
    id: ts_light_guition_esp32_jc4827w543c_display_backlight
    entity_id: light.guition_esp32_jc4827w543c_display_backlight
    on_value:
      then:
        - lvgl.widget.update:
            id: btn_12
            state:
              checked: !lambda return (0 == x.compare(std::string{"on"}));
              disabled: !lambda return ((0 == x.compare(std::string{"unavailable"})) or (0 == x.compare(std::string{"unknown"})));
        - lvgl.label.update:
            id: lbl_btn_12
            text: !lambda |-
              static char buf[10];
              std::string icon;
              if (0 == x.compare(std::string{"on"})) {
                  icon = "󰤝";
              } else {
                  icon = "󱟉";
              }
              snprintf(buf, sizeof(buf), "%s", icon.c_str());
              return buf;



# Touchscreen configuration
i2c:
  - id: bus_a
    sda: 8
    scl: 4
    scan: true

touchscreen:
  - platform: gt911
    id: my_touchscreen
    i2c_id: bus_a
    interrupt_pin:
      number: 3
      ignore_strapping_warning: true
    reset_pin: 38

# Display configuration
spi:
  id: quad_spi
  type: quad
  clk_pin: 47
  data_pins: [21,48,40,39]

display:
  - platform: qspi_dbi
    id: my_display
    update_interval: never
    auto_clear_enabled: False
    model: CUSTOM
    data_rate: 20MHz
    dimensions:
      width: 480
      height: 272
    cs_pin:
      number: 45
      ignore_strapping_warning: true
    invert_colors: true
    rotation: 180
    init_sequence:
      - [0xff,0xa5]
      - [0x36,0xc0]
      - [0x3A,0x01]
      - [0x41,0x03]
      - [0x44,0x15]
      - [0x45,0x15]
      - [0x7d,0x03]
      - [0xc1,0xbb]
      - [0xc2,0x05]
      - [0xc3,0x10]
      - [0xc6,0x3e]
      - [0xc7,0x25]
      - [0xc8,0x11]
      - [0x7a,0x5f]
      - [0x6f,0x44]
      - [0x78,0x70]
      - [0xc9,0x00]
      - [0x67,0x21]
      - [0x51,0x0a]
      - [0x52,0x76]
      - [0x53,0x0a]
      - [0x54,0x76]
      - [0x46,0x0a]
      - [0x47,0x2a]
      - [0x48,0x0a]
      - [0x49,0x1a]
      - [0x56,0x43]
      - [0x57,0x42]
      - [0x58,0x3c]
      - [0x59,0x64]
      - [0x5a,0x41]
      - [0x5b,0x3c]
      - [0x5c,0x02]
      - [0x5d,0x3c]
      - [0x5e,0x1f]
      - [0x60,0x80]
      - [0x61,0x3f]
      - [0x62,0x21]
      - [0x63,0x07]
      - [0x64,0xe0]
      - [0x65,0x02]
      - [0xca,0x20]
      - [0xcb,0x52]
      - [0xcc,0x10]
      - [0xcd,0x42]
      - [0xd0,0x20]
      - [0xd1,0x52]
      - [0xd2,0x10]
      - [0xd3,0x42]
      - [0xd4,0x0a]
      - [0xd5,0x32]
      - [0x80,0x00]
      - [0xa0,0x00]
      - [0x81,0x07]
      - [0xa1,0x06]
      - [0x82,0x02]
      - [0xa2,0x01]
      - [0x86,0x11]
      - [0xa6,0x10]
      - [0x87,0x27]
      - [0xa7,0x27]
      - [0x83,0x37]
      - [0xa3,0x37]
      - [0x84,0x35]
      - [0xa4,0x35]
      - [0x85,0x3f]
      - [0xa5,0x3f]
      - [0x88,0x0b]
      - [0xa8,0x0b]
      - [0x89,0x14]
      - [0xa9,0x14]
      - [0x8a,0x1a]
      - [0xaa,0x1a]
      - [0x8b,0x0a]
      - [0xab,0x0a]
      - [0x8c,0x14]
      - [0xac,0x08]
      - [0x8d,0x17]
      - [0xad,0x07]
      - [0x8e,0x16]
      - [0xae,0x06]
      - [0x8f,0x1B]
      - [0xaf,0x07]
      - [0x90,0x04]
      - [0xb0,0x04]
      - [0x91,0x0a]
      - [0xb1,0x0a]
      - [0x92,0x16]
      - [0xb2,0x15]
      - [0xff,0x00]
      - [0x11,0x00]
      - [0x29,0x00]

# LVGL UI configuration
lvgl:
  buffer_size: 25%
  displays:
    - my_display
  touchscreens:
    - my_touchscreen
  page_wrap: false
  theme:
    button:
      bg_color: default_button_bg_color  # Now uses 25262B
      radius: 4
      border_width: 0  # Removed borders
      text_color: 0xFFFFFF
      pressed:
        bg_color: 0x333333
      checked:
        bg_color: 0x4CAF50  # Green
        text_color: 0x000000
  pages:
    - id: main_page
      pad_all: 0
      widgets:
        - obj:
            width: 480
            height: 272
            bg_color: room_bg_color
            layout:
              type: grid
              grid_columns: [fr(1), fr(1), fr(1), fr(1)]
              grid_rows: [fr(1), fr(1), fr(1)]
            pad_all: 5px
            outline_pad: 1px
            widgets:
                            
              # Corrected Button 1 configuration:
              - button:
                  id: btn_1
                  grid_cell_column_pos: 0
                  grid_cell_row_pos: 0
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: STRETCH
                  bg_color: default_button_bg_color
                  checkable: true
                  widgets:
                    - label:
                        id: lbl_btn_1
                        text: "󰤝"
                        text_font: font_mdi
                        align: center
                  on_click:
                    then:
                      - homeassistant.action:
                          action: switch.toggle  # Fixed typo "swtich" to "switch"
                          data:
                            entity_id: REDACTED
                      - binary_sensor.template.publish:
                          id: button_1_pressed
                          state: ON
                      - delay: 500ms
                      - binary_sensor.template.publish:
                          id: button_1_pressed
                          state: OFF
              
              # Corrected Button 2 configuration:
              - button:
                  id: btn_2
                  grid_cell_column_pos: 1
                  grid_cell_row_pos: 0
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: STRETCH
                  bg_color: default_button_bg_color
                  checkable: true
                  widgets:
                    - label:
                        id: lbl_btn_2
                        text: "󰤝"
                        text_font: font_mdi
                        align: center
                  on_click:
                    then:
                      - homeassistant.action:  # Added missing Home Assistant action
                          action: switch.toggle
                          data:
                            entity_id: REDACTED
                      - binary_sensor.template.publish:
                          id: button_2_pressed
                          state: ON
                      - delay: 500ms
                      - binary_sensor.template.publish:
                          id: button_2_pressed
                          state: OFF
              
              # Corrected Button 3 configuration:
              - button:
                  id: btn_3
                  grid_cell_column_pos: 2
                  grid_cell_row_pos: 0
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: STRETCH
                  bg_color: default_button_bg_color
                  checkable: true
                  widgets:
                    - label:
                        id: lbl_btn_3
                        text: "󰤝"
                        text_font: font_mdi
                        align: center
                  on_click:
                    then:
                      - homeassistant.action:  # Added missing Home Assistant action
                          action: switch.toggle
                          data:
                            entity_id: REDACTED
                      - binary_sensor.template.publish:
                          id: button_3_pressed
                          state: ON
                      - delay: 500ms
                      - binary_sensor.template.publish:
                          id: button_3_pressed
                          state: OFF
              # Button 4(controls light.h6159)
              - button:
                  id: btn_4
                  grid_cell_column_pos: 3
                  grid_cell_row_pos: 0
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: STRETCH
                  bg_color: default_button_bg_color
                  checkable: true
                  widgets:
                    - label:
                        id: lbl_btn_4
                        text: "󰤝"
                        text_font: font_mdi
                        align: center
                  on_click:
                    then:
                      - homeassistant.action:
                          action: light.toggle
                          data:
                            entity_id: REDACTED
                      - binary_sensor.template.publish:
                          id: button_4_pressed
                          state: ON
                      - delay: 500ms
                      - binary_sensor.template.publish:
                          id: button_4_pressed
                          state: OFF
                            # Continue with buttons 3-11 following the same pattern...
              
              # Button 12 (controls light.h6159)
              - button:
                  id: btn_12
                  grid_cell_column_pos: 3
                  grid_cell_row_pos: 2
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: STRETCH
                  bg_color: default_button_bg_color
                  checkable: true
                  widgets:
                    - label:
                        id: lbl_btn_12
                        text: "󰤝"
                        text_font: font_mdi
                        align: center
                  on_click:
                    then:
                      - homeassistant.action:
                          action: light.toggle
                          data:
                            entity_id: light.guition_esp32_jc4827w543c_display_backlight
                      - binary_sensor.template.publish:
                          id: button_12_pressed
                          state: ON
                      - delay: 500ms
                      - binary_sensor.template.publish:
                          id: button_12_pressed
                          state: OFF
